-- Vocabulary Seeds for Word Rush Feature
-- 500 Core Spanish Words based on CEFR Frequency Lists
-- Sources: Instituto Cervantes, Spanish Frequency Dictionary, CEFR Wordlists
-- Distribution: ~100 A0, ~250 A1, ~150 A2

-- ============================================================================
-- A0 LEVEL (100 words) - Absolute Beginners
-- Ultra-basic: articles, pronouns, numbers, colors, family, body parts
-- ============================================================================

INSERT INTO vocabulary (english_word, spanish_word, difficulty_level, category, illustration_emoji, is_core, source) VALUES

-- Articles & Basic Grammar (10)
('the (masc)', 'el', 'A0', 'grammar', '📝', true, 'seeded'),
('the (fem)', 'la', 'A0', 'grammar', '📝', true, 'seeded'),
('a/an (masc)', 'un', 'A0', 'grammar', '1️⃣', true, 'seeded'),
('a/an (fem)', 'una', 'A0', 'grammar', '1️⃣', true, 'seeded'),
('of/from', 'de', 'A0', 'grammar', '➡️', true, 'seeded'),
('and', 'y', 'A0', 'grammar', '➕', true, 'seeded'),
('in/on', 'en', 'A0', 'grammar', '📍', true, 'seeded'),
('to/at', 'a', 'A0', 'grammar', '🎯', true, 'seeded'),
('that', 'que', 'A0', 'grammar', '👉', true, 'seeded'),
('is (he/she)', 'es', 'A0', 'verbs', '✅', true, 'seeded'),

-- Numbers 1-10 (10)
('one', 'uno', 'A0', 'numbers', '1️⃣', true, 'seeded'),
('two', 'dos', 'A0', 'numbers', '2️⃣', true, 'seeded'),
('three', 'tres', 'A0', 'numbers', '3️⃣', true, 'seeded'),
('four', 'cuatro', 'A0', 'numbers', '4️⃣', true, 'seeded'),
('five', 'cinco', 'A0', 'numbers', '5️⃣', true, 'seeded'),
('six', 'seis', 'A0', 'numbers', '6️⃣', true, 'seeded'),
('seven', 'siete', 'A0', 'numbers', '7️⃣', true, 'seeded'),
('eight', 'ocho', 'A0', 'numbers', '8️⃣', true, 'seeded'),
('nine', 'nueve', 'A0', 'numbers', '9️⃣', true, 'seeded'),
('ten', 'diez', 'A0', 'numbers', '🔟', true, 'seeded'),

-- Basic Colors (8)
('red', 'rojo', 'A0', 'colors', '🔴', true, 'seeded'),
('blue', 'azul', 'A0', 'colors', '🔵', true, 'seeded'),
('yellow', 'amarillo', 'A0', 'colors', '🟡', true, 'seeded'),
('green', 'verde', 'A0', 'colors', '🟢', true, 'seeded'),
('white', 'blanco', 'A0', 'colors', '⚪', true, 'seeded'),
('black', 'negro', 'A0', 'colors', '⚫', true, 'seeded'),
('orange', 'naranja', 'A0', 'colors', '🟠', true, 'seeded'),
('pink', 'rosa', 'A0', 'colors', '🌸', true, 'seeded'),

-- Family (10)
('mom', 'mamá', 'A0', 'family', '👩', true, 'seeded'),
('dad', 'papá', 'A0', 'family', '👨', true, 'seeded'),
('grandma', 'abuela', 'A0', 'family', '👵', true, 'seeded'),
('grandpa', 'abuelo', 'A0', 'family', '👴', true, 'seeded'),
('brother', 'hermano', 'A0', 'family', '👦', true, 'seeded'),
('sister', 'hermana', 'A0', 'family', '👧', true, 'seeded'),
('son', 'hijo', 'A0', 'family', '🧒', true, 'seeded'),
('daughter', 'hija', 'A0', 'family', '👧', true, 'seeded'),
('baby', 'bebé', 'A0', 'family', '👶', true, 'seeded'),
('child', 'niño', 'A0', 'family', '🧒', true, 'seeded'),

-- Basic Animals (12)
('dog', 'perro', 'A0', 'animals', '🐕', true, 'seeded'),
('cat', 'gato', 'A0', 'animals', '🐱', true, 'seeded'),
('bird', 'pájaro', 'A0', 'animals', '🐦', true, 'seeded'),
('fish', 'pez', 'A0', 'animals', '🐟', true, 'seeded'),
('cow', 'vaca', 'A0', 'animals', '🐮', true, 'seeded'),
('horse', 'caballo', 'A0', 'animals', '🐴', true, 'seeded'),
('chicken', 'pollo', 'A0', 'animals', '🐔', true, 'seeded'),
('pig', 'cerdo', 'A0', 'animals', '🐷', true, 'seeded'),
('duck', 'pato', 'A0', 'animals', '🦆', true, 'seeded'),
('mouse', 'ratón', 'A0', 'animals', '🐭', true, 'seeded'),
('rabbit', 'conejo', 'A0', 'animals', '🐰', true, 'seeded'),
('monkey', 'mono', 'A0', 'animals', '🐵', true, 'seeded'),

-- Basic Food & Drink (15)
('water', 'agua', 'A0', 'food', '💧', true, 'seeded'),
('milk', 'leche', 'A0', 'food', '🥛', true, 'seeded'),
('bread', 'pan', 'A0', 'food', '🍞', true, 'seeded'),
('apple', 'manzana', 'A0', 'food', '🍎', true, 'seeded'),
('banana', 'plátano', 'A0', 'food', '🍌', true, 'seeded'),
('orange (fruit)', 'naranja', 'A0', 'food', '🍊', true, 'seeded'),
('egg', 'huevo', 'A0', 'food', '🥚', true, 'seeded'),
('cheese', 'queso', 'A0', 'food', '🧀', true, 'seeded'),
('rice', 'arroz', 'A0', 'food', '🍚', true, 'seeded'),
('meat', 'carne', 'A0', 'food', '🍖', true, 'seeded'),
('juice', 'jugo', 'A0', 'food', '🧃', true, 'seeded'),
('coffee', 'café', 'A0', 'food', '☕', true, 'seeded'),
('tea', 'té', 'A0', 'food', '🍵', true, 'seeded'),
('soup', 'sopa', 'A0', 'food', '🍲', true, 'seeded'),
('cake', 'pastel', 'A0', 'food', '🎂', true, 'seeded'),

-- Body Parts (10)
('head', 'cabeza', 'A0', 'body', '🗣️', true, 'seeded'),
('hand', 'mano', 'A0', 'body', '🖐️', true, 'seeded'),
('foot', 'pie', 'A0', 'body', '🦶', true, 'seeded'),
('eye', 'ojo', 'A0', 'body', '👁️', true, 'seeded'),
('mouth', 'boca', 'A0', 'body', '👄', true, 'seeded'),
('nose', 'nariz', 'A0', 'body', '👃', true, 'seeded'),
('ear', 'oreja', 'A0', 'body', '👂', true, 'seeded'),
('hair', 'pelo', 'A0', 'body', '💇', true, 'seeded'),
('arm', 'brazo', 'A0', 'body', '💪', true, 'seeded'),
('leg', 'pierna', 'A0', 'body', '🦵', true, 'seeded'),

-- Common Greetings & Phrases (10)
('hello', 'hola', 'A0', 'greetings', '👋', true, 'seeded'),
('goodbye', 'adiós', 'A0', 'greetings', '👋', true, 'seeded'),
('please', 'por favor', 'A0', 'greetings', '🙏', true, 'seeded'),
('thank you', 'gracias', 'A0', 'greetings', '💝', true, 'seeded'),
('yes', 'sí', 'A0', 'greetings', '✅', true, 'seeded'),
('no', 'no', 'A0', 'greetings', '❌', true, 'seeded'),
('good morning', 'buenos días', 'A0', 'greetings', '🌅', true, 'seeded'),
('good night', 'buenas noches', 'A0', 'greetings', '🌙', true, 'seeded'),
('excuse me', 'perdón', 'A0', 'greetings', '🙇', true, 'seeded'),
('sorry', 'lo siento', 'A0', 'greetings', '😔', true, 'seeded'),

-- Days of Week (7)
('Monday', 'lunes', 'A0', 'time', '📅', true, 'seeded'),
('Tuesday', 'martes', 'A0', 'time', '📅', true, 'seeded'),
('Wednesday', 'miércoles', 'A0', 'time', '📅', true, 'seeded'),
('Thursday', 'jueves', 'A0', 'time', '📅', true, 'seeded'),
('Friday', 'viernes', 'A0', 'time', '📅', true, 'seeded'),
('Saturday', 'sábado', 'A0', 'time', '📅', true, 'seeded'),
('Sunday', 'domingo', 'A0', 'time', '📅', true, 'seeded'),

-- Basic Objects (8)
('house', 'casa', 'A0', 'objects', '🏠', true, 'seeded'),
('car', 'coche', 'A0', 'objects', '🚗', true, 'seeded'),
('book', 'libro', 'A0', 'objects', '📖', true, 'seeded'),
('table', 'mesa', 'A0', 'objects', '🪑', true, 'seeded'),
('chair', 'silla', 'A0', 'objects', '🪑', true, 'seeded'),
('door', 'puerta', 'A0', 'objects', '🚪', true, 'seeded'),
('window', 'ventana', 'A0', 'objects', '🪟', true, 'seeded'),
('bed', 'cama', 'A0', 'objects', '🛏️', true, 'seeded');

-- ============================================================================
-- A1 LEVEL (250 words) - Beginners
-- Everyday situations, common verbs, basic adjectives
-- ============================================================================

INSERT INTO vocabulary (english_word, spanish_word, difficulty_level, category, illustration_emoji, is_core, source) VALUES

-- Essential Verbs (50)
('to be (permanent)', 'ser', 'A1', 'verbs', '✨', true, 'seeded'),
('to be (temporary)', 'estar', 'A1', 'verbs', '📍', true, 'seeded'),
('to have', 'tener', 'A1', 'verbs', '🤲', true, 'seeded'),
('to do/make', 'hacer', 'A1', 'verbs', '⚙️', true, 'seeded'),
('to go', 'ir', 'A1', 'verbs', '🚶', true, 'seeded'),
('to come', 'venir', 'A1', 'verbs', '👋', true, 'seeded'),
('to want', 'querer', 'A1', 'verbs', '💭', true, 'seeded'),
('to can/be able', ' poder', 'A1', 'verbs', '💪', true, 'seeded'),
('to know (facts)', 'saber', 'A1', 'verbs', '🧠', true, 'seeded'),
('to know (people)', 'conocer', 'A1', 'verbs', '👤', true, 'seeded'),
('to eat', 'comer', 'A1', 'verbs', '🍽️', true, 'seeded'),
('to drink', 'beber', 'A1', 'verbs', '🥤', true, 'seeded'),
('to speak', 'hablar', 'A1', 'verbs', '🗣️', true, 'seeded'),
('to listen', 'escuchar', 'A1', 'verbs', '👂', true, 'seeded'),
('to see', 'ver', 'A1', 'verbs', '👁️', true, 'seeded'),
('to look at', 'mirar', 'A1', 'verbs', '👀', true, 'seeded'),
('to read', 'leer', 'A1', 'verbs', '📖', true, 'seeded'),
('to write', 'escribir', 'A1', 'verbs', '✍️', true, 'seeded'),
('to live', 'vivir', 'A1', 'verbs', '🏠', true, 'seeded'),
('to work', 'trabajar', 'A1', 'verbs', '💼', true, 'seeded'),
('to study', 'estudiar', 'A1', 'verbs', '📚', true, 'seeded'),
('to learn', 'aprender', 'A1', 'verbs', '🎓', true, 'seeded'),
('to teach', 'enseñar', 'A1', 'verbs', '👨‍🏫', true, 'seeded'),
('to play', 'jugar', 'A1', 'verbs', '🎮', true, 'seeded'),
('to sleep', 'dormir', 'A1', 'verbs', '😴', true, 'seeded'),
('to wake up', 'despertar', 'A1', 'verbs', '⏰', true, 'seeded'),
('to get up', 'levantarse', 'A1', 'verbs', '🛏️', true, 'seeded'),
('to sit down', 'sentarse', 'A1', 'verbs', '🪑', true, 'seeded'),
('to open', 'abrir', 'A1', 'verbs', '🔓', true, 'seeded'),
('to close', 'cerrar', 'A1', 'verbs', '🔒', true, 'seeded'),
('to give', 'dar', 'A1', 'verbs', '🎁', true, 'seeded'),
('to take', 'tomar', 'A1', 'verbs', '✋', true, 'seeded'),
('to put', 'poner', 'A1', 'verbs', '📦', true, 'seeded'),
('to buy', 'comprar', 'A1', 'verbs', '🛒', true, 'seeded'),
('to sell', 'vender', 'A1', 'verbs', '💰', true, 'seeded'),
('to need', 'necesitar', 'A1', 'verbs', '❗', true, 'seeded'),
('to like', 'gustar', 'A1', 'verbs', '❤️', true, 'seeded'),
('to love', 'amar', 'A1', 'verbs', '💕', true, 'seeded'),
('to help', 'ayudar', 'A1', 'verbs', '🤝', true, 'seeded'),
('to call', 'llamar', 'A1', 'verbs', '📞', true, 'seeded'),
('to ask', 'preguntar', 'A1', 'verbs', '❓', true, 'seeded'),
('to answer', 'responder', 'A1', 'verbs', '💬', true, 'seeded'),
('to walk', 'caminar', 'A1', 'verbs', '🚶', true, 'seeded'),
('to run', 'correr', 'A1', 'verbs', '🏃', true, 'seeded'),
('to jump', 'saltar', 'A1', 'verbs', '🦘', true, 'seeded'),
('to dance', 'bailar', 'A1', 'verbs', '💃', true, 'seeded'),
('to sing', 'cantar', 'A1', 'verbs', '🎤', true, 'seeded'),
('to cook', 'cocinar', 'A1', 'verbs', '🍳', true, 'seeded'),
('to clean', 'limpiar', 'A1', 'verbs', '🧹', true, 'seeded'),
('to wash', 'lavar', 'A1', 'verbs', '🧼', true, 'seeded'),

-- Common Adjectives (40)
('big', 'grande', 'A1', 'adjectives', '📏', true, 'seeded'),
('small', 'pequeño', 'A1', 'adjectives', '🔬', true, 'seeded'),
('good', 'bueno', 'A1', 'adjectives', '👍', true, 'seeded'),
('bad', 'malo', 'A1', 'adjectives', '👎', true, 'seeded'),
('pretty/beautiful', 'bonito', 'A1', 'adjectives', '✨', true, 'seeded'),
('ugly', 'feo', 'A1', 'adjectives', '😖', true, 'seeded'),
('new', 'nuevo', 'A1', 'adjectives', '🆕', true, 'seeded'),
('old (things)', 'viejo', 'A1', 'adjectives', '🕰️', true, 'seeded'),
('young', 'joven', 'A1', 'adjectives', '👶', true, 'seeded'),
('old (people)', 'mayor', 'A1', 'adjectives', '👴', true, 'seeded'),
('hot', 'caliente', 'A1', 'adjectives', '🔥', true, 'seeded'),
('cold', 'frío', 'A1', 'adjectives', '❄️', true, 'seeded'),
('happy', 'feliz', 'A1', 'adjectives', '😊', true, 'seeded'),
('sad', 'triste', 'A1', 'adjectives', '😢', true, 'seeded'),
('tired', 'cansado', 'A1', 'adjectives', '😴', true, 'seeded'),
('hungry', 'hambriento', 'A1', 'adjectives', '🍽️', true, 'seeded'),
('thirsty', 'sediento', 'A1', 'adjectives', '💧', true, 'seeded'),
('tall', 'alto', 'A1', 'adjectives', '📐', true, 'seeded'),
('short (height)', 'bajo', 'A1', 'adjectives', '📏', true, 'seeded'),
('long', 'largo', 'A1', 'adjectives', '📏', true, 'seeded'),
('short (length)', 'corto', 'A1', 'adjectives', '✂️', true, 'seeded'),
('fast', 'rápido', 'A1', 'adjectives', '⚡', true, 'seeded'),
('slow', 'lento', 'A1', 'adjectives', '🐌', true, 'seeded'),
('easy', 'fácil', 'A1', 'adjectives', '👌', true, 'seeded'),
('difficult', 'difícil', 'A1', 'adjectives', '😰', true, 'seeded'),
('clean', 'limpio', 'A1', 'adjectives', '✨', true, 'seeded'),
('dirty', 'sucio', 'A1', 'adjectives', '🧹', true, 'seeded'),
('expensive', 'caro', 'A1', 'adjectives', '💰', true, 'seeded'),
('cheap', 'barato', 'A1', 'adjectives', '💸', true, 'seeded'),
('full', 'lleno', 'A1', 'adjectives', '📦', true, 'seeded'),
('empty', 'vacío', 'A1', 'adjectives', '📭', true, 'seeded'),
('open', 'abierto', 'A1', 'adjectives', '🔓', true, 'seeded'),
('closed', 'cerrado', 'A1', 'adjectives', '🔒', true, 'seeded'),
('right (correct)', 'correcto', 'A1', 'adjectives', '✅', true, 'seeded'),
('wrong', 'incorrecto', 'A1', 'adjectives', '❌', true, 'seeded'),
('sick', 'enfermo', 'A1', 'adjectives', '🤒', true, 'seeded'),
('healthy', 'sano', 'A1', 'adjectives', '💪', true, 'seeded'),
('rich', 'rico', 'A1', 'adjectives', '💵', true, 'seeded'),
('poor', 'pobre', 'A1', 'adjectives', '🙏', true, 'seeded'),
('free', 'libre', 'A1', 'adjectives', '🆓', true, 'seeded'),

-- More Numbers & Time (20)
('eleven', 'once', 'A1', 'numbers', '1️⃣1️⃣', true, 'seeded'),
('twelve', 'doce', 'A1', 'numbers', '1️⃣2️⃣', true, 'seeded'),
('thirteen', 'trece', 'A1', 'numbers', '1️⃣3️⃣', true, 'seeded'),
('fourteen', 'catorce', 'A1', 'numbers', '1️⃣4️⃣', true, 'seeded'),
('fifteen', 'quince', 'A1', 'numbers', '1️⃣5️⃣', true, 'seeded'),
('twenty', 'veinte', 'A1', 'numbers', '2️⃣0️⃣', true, 'seeded'),
('thirty', 'treinta', 'A1', 'numbers', '3️⃣0️⃣', true, 'seeded'),
('forty', 'cuarenta', 'A1', 'numbers', '4️⃣0️⃣', true, 'seeded'),
('fifty', 'cincuenta', 'A1', 'numbers', '5️⃣0️⃣', true, 'seeded'),
('hundred', 'cien', 'A1', 'numbers', '💯', true, 'seeded'),
('today', 'hoy', 'A1', 'time', '📅', true, 'seeded'),
('yesterday', 'ayer', 'A1', 'time', '◀️', true, 'seeded'),
('tomorrow', 'mañana', 'A1', 'time', '▶️', true, 'seeded'),
('morning', 'mañana', 'A1', 'time', '🌅', true, 'seeded'),
('afternoon', 'tarde', 'A1', 'time', '🌇', true, 'seeded'),
('night', 'noche', 'A1', 'time', '🌙', true, 'seeded'),
('day', 'día', 'A1', 'time', '☀️', true, 'seeded'),
('week', 'semana', 'A1', 'time', '📅', true, 'seeded'),
('month', 'mes', 'A1', 'time', '🗓️', true, 'seeded'),
('year', 'año', 'A1', 'time', '📆', true, 'seeded'),

-- Places & Locations (30)
('school', 'escuela', 'A1', 'places', '🏫', true, 'seeded'),
('park', 'parque', 'A1', 'places', '🌳', true, 'seeded'),
('store', 'tienda', 'A1', 'places', '🏪', true, 'seeded'),
('restaurant', 'restaurante', 'A1', 'places', '🍽️', true, 'seeded'),
('hospital', 'hospital', 'A1', 'places', '🏥', true, 'seeded'),
('church', 'iglesia', 'A1', 'places', '⛪', true, 'seeded'),
('street', 'calle', 'A1', 'places', '🛣️', true, 'seeded'),
('city', 'ciudad', 'A1', 'places', '🏙️', true, 'seeded'),
('country', 'país', 'A1', 'places', '🗺️', true, 'seeded'),
('beach', 'playa', 'A1', 'places', '🏖️', true, 'seeded'),
('mountain', 'montaña', 'A1', 'places', '⛰️', true, 'seeded'),
('river', 'río', 'A1', 'places', '🌊', true, 'seeded'),
('sea', 'mar', 'A1', 'places', '🌊', true, 'seeded'),
('kitchen', 'cocina', 'A1', 'places', '🍳', true, 'seeded'),
('bathroom', 'baño', 'A1', 'places', '🚿', true, 'seeded'),
('bedroom', 'dormitorio', 'A1', 'places', '🛏️', true, 'seeded'),
('living room', 'sala', 'A1', 'places', '🛋️', true, 'seeded'),
('garden', 'jardín', 'A1', 'places', '🌺', true, 'seeded'),
('office', 'oficina', 'A1', 'places', '🏢', true, 'seeded'),
('library', 'biblioteca', 'A1', 'places', '📚', true, 'seeded'),
('market', 'mercado', 'A1', 'places', '🛒', true, 'seeded'),
('hotel', 'hotel', 'A1', 'places', '🏨', true, 'seeded'),
('airport', 'aeropuerto', 'A1', 'places', '✈️', true, 'seeded'),
('station', 'estación', 'A1', 'places', '🚉', true, 'seeded'),
('museum', 'museo', 'A1', 'places', '🖼️', true, 'seeded'),
('cinema', 'cine', 'A1', 'places', '🎬', true, 'seeded'),
('room', 'habitación', 'A1', 'places', '🚪', true, 'seeded'),
('floor', 'piso', 'A1', 'places', '🏢', true, 'seeded'),
('roof', 'techo', 'A1', 'places', '🏠', true, 'seeded'),
('wall', 'pared', 'A1', 'places', '🧱', true, 'seeded'),

-- Weather & Nature (15)
('sun', 'sol', 'A1', 'nature', '☀️', true, 'seeded'),
('moon', 'luna', 'A1', 'nature', '🌙', true, 'seeded'),
('star', 'estrella', 'A1', 'nature', '⭐', true, 'seeded'),
('rain', 'lluvia', 'A1', 'nature', '🌧️', true, 'seeded'),
('snow', 'nieve', 'A1', 'nature', '❄️', true, 'seeded'),
('wind', 'viento', 'A1', 'nature', '💨', true, 'seeded'),
('cloud', 'nube', 'A1', 'nature', '☁️', true, 'seeded'),
('tree', 'árbol', 'A1', 'nature', '🌳', true, 'seeded'),
('flower', 'flor', 'A1', 'nature', '🌸', true, 'seeded'),
('grass', 'hierba', 'A1', 'nature', '🌱', true, 'seeded'),
('plant', 'planta', 'A1', 'nature', '🌿', true, 'seeded'),
('stone', 'piedra', 'A1', 'nature', '🪨', true, 'seeded'),
('fire', 'fuego', 'A1', 'nature', '🔥', true, 'seeded'),
('earth', 'tierra', 'A1', 'nature', '🌍', true, 'seeded'),
('sky', 'cielo', 'A1', 'nature', '🌌', true, 'seeded'),

-- Transportation (10)
('bus', 'autobús', 'A1', 'transport', '🚌', true, 'seeded'),
('train', 'tren', 'A1', 'transport', '🚂', true, 'seeded'),
('bicycle', 'bicicleta', 'A1', 'transport', '🚲', true, 'seeded'),
('motorcycle', 'moto', 'A1', 'transport', '🏍️', true, 'seeded'),
('airplane', 'avión', 'A1', 'transport', '✈️', true, 'seeded'),
('boat', 'barco', 'A1', 'transport', '⛵', true, 'seeded'),
('taxi', 'taxi', 'A1', 'transport', '🚕', true, 'seeded'),
('truck', 'camión', 'A1', 'transport', '🚚', true, 'seeded'),
('ship', 'barco', 'A1', 'transport', '🚢', true, 'seeded'),
('helicopter', 'helicóptero', 'A1', 'transport', '🚁', true, 'seeded'),

-- Clothing (15)
('shirt', 'camisa', 'A1', 'clothing', '👕', true, 'seeded'),
('pants', 'pantalones', 'A1', 'clothing', '👖', true, 'seeded'),
('dress', 'vestido', 'A1', 'clothing', '👗', true, 'seeded'),
('skirt', 'falda', 'A1', 'clothing', '👗', true, 'seeded'),
('shoes', 'zapatos', 'A1', 'clothing', '👞', true, 'seeded'),
('socks', 'calcetines', 'A1', 'clothing', '🧦', true, 'seeded'),
('hat', 'sombrero', 'A1', 'clothing', '🎩', true, 'seeded'),
('jacket', 'chaqueta', 'A1', 'clothing', '🧥', true, 'seeded'),
('coat', 'abrigo', 'A1', 'clothing', '🧥', true, 'seeded'),
('sweater', 'suéter', 'A1', 'clothing', '🧶', true, 'seeded'),
('gloves', 'guantes', 'A1', 'clothing', '🧤', true, 'seeded'),
('scarf', 'bufanda', 'A1', 'clothing', '🧣', true, 'seeded'),
('belt', 'cinturón', 'A1', 'clothing', '👖', true, 'seeded'),
('glasses', 'gafas', 'A1', 'clothing', '👓', true, 'seeded'),
('watch', 'reloj', 'A1', 'clothing', '⌚', true, 'seeded'),

-- Professions (15)
('teacher', 'profesor', 'A1', 'professions', '👨‍🏫', true, 'seeded'),
('doctor', 'médico', 'A1', 'professions', '👨‍⚕️', true, 'seeded'),
('nurse', 'enfermera', 'A1', 'professions', '👩‍⚕️', true, 'seeded'),
('police officer', 'policía', 'A1', 'professions', '👮', true, 'seeded'),
('firefighter', 'bombero', 'A1', 'professions', '👨‍🚒', true, 'seeded'),
('cook', 'cocinero', 'A1', 'professions', '👨‍🍳', true, 'seeded'),
('artist', 'artista', 'A1', 'professions', '🎨', true, 'seeded'),
('musician', 'músico', 'A1', 'professions', '🎵', true, 'seeded'),
('writer', 'escritor', 'A1', 'professions', '✍️', true, 'seeded'),
('student', 'estudiante', 'A1', 'professions', '🎓', true, 'seeded'),
('worker', 'trabajador', 'A1', 'professions', '👷', true, 'seeded'),
('driver', 'conductor', 'A1', 'professions', '🚗', true, 'seeded'),
('farmer', 'agricultor', 'A1', 'professions', '👨‍🌾', true, 'seeded'),
('baker', 'panadero', 'A1', 'professions', '🥖', true, 'seeded'),
('waiter', 'camarero', 'A1', 'professions', '🍽️', true, 'seeded'),

-- More Food (15)
('potato', 'patata', 'A1', 'food', '🥔', true, 'seeded'),
('tomato', 'tomate', 'A1', 'food', '🍅', true, 'seeded'),
('onion', 'cebolla', 'A1', 'food', '🧅', true, 'seeded'),
('carrot', 'zanahoria', 'A1', 'food', '🥕', true, 'seeded'),
('lettuce', 'lechuga', 'A1', 'food', '🥬', true, 'seeded'),
('salad', 'ensalada', 'A1', 'food', '🥗', true, 'seeded'),
('pizza', 'pizza', 'A1', 'food', '🍕', true, 'seeded'),
('hamburger', 'hamburguesa', 'A1', 'food', '🍔', true, 'seeded'),
('sandwich', 'sándwich', 'A1', 'food', '🥪', true, 'seeded'),
('ice cream', 'helado', 'A1', 'food', '🍦', true, 'seeded'),
('chocolate', 'chocolate', 'A1', 'food', '🍫', true, 'seeded'),
('butter', 'mantequilla', 'A1', 'food', '🧈', true, 'seeded'),
('oil', 'aceite', 'A1', 'food', '🫒', true, 'seeded'),
('salt', 'sal', 'A1', 'food', '🧂', true, 'seeded'),
('sugar', 'azúcar', 'A1', 'food', '🍬', true, 'seeded');

-- Continue in next file due to character limit...
-- This is approximately 350 words so far. Need to add ~150 more A2 words.
