-- Vocabulary Seeds for Word Rush Feature - PART 2
-- Remaining A2 Level Words (150 words)
-- Sources: Instituto Cervantes, Spanish Frequency Dictionary, CEFR Wordlists

-- ============================================================================
-- A2 LEVEL (150 words) - Elementary
-- Complex sentences, past/future tenses, opinions, descriptions
-- ============================================================================

INSERT INTO vocabulary (english_word, spanish_word, difficulty_level, category, illustration_emoji, is_core, source) VALUES

-- Advanced Verbs (40)
('to think', 'pensar', 'A2', 'verbs', '🤔', true, 'seeded'),
('to believe', 'creer', 'A2', 'verbs', '💭', true, 'seeded'),
('to feel', 'sentir', 'A2', 'verbs', '❤️', true, 'seeded'),
('to remember', 'recordar', 'A2', 'verbs', '🧠', true, 'seeded'),
('to forget', 'olvidar', 'A2', 'verbs', '🤷', true, 'seeded'),
('to understand', 'entender', 'A2', 'verbs', '💡', true, 'seeded'),
('to explain', 'explicar', 'A2', 'verbs', '📝', true, 'seeded'),
('to try', 'intentar', 'A2', 'verbs', '🎯', true, 'seeded'),
('to decide', 'decidir', 'A2', 'verbs', '🤔', true, 'seeded'),
('to choose', 'elegir', 'A2', 'verbs', '☑️', true, 'seeded'),
('to prefer', 'preferir', 'A2', 'verbs', '⭐', true, 'seeded'),
('to hope', 'esperar', 'A2', 'verbs', '🙏', true, 'seeded'),
('to wish', 'desear', 'A2', 'verbs', '🌟', true, 'seeded'),
('to win', 'ganar', 'A2', 'verbs', '🏆', true, 'seeded'),
('to lose', 'perder', 'A2', 'verbs', '😔', true, 'seeded'),
('to find', 'encontrar', 'A2', 'verbs', '🔍', true, 'seeded'),
('to search', 'buscar', 'A2', 'verbs', '🔎', true, 'seeded'),
('to meet', 'conocer', 'A2', 'verbs', '🤝', true, 'seeded'),
('to visit', 'visitar', 'A2', 'verbs', '🚪', true, 'seeded'),
('to travel', 'viajar', 'A2', 'verbs', '🧳', true, 'seeded'),
('to arrive', 'llegar', 'A2', 'verbs', '🎯', true, 'seeded'),
('to leave', 'salir', 'A2', 'verbs', '🚪', true, 'seeded'),
('to enter', 'entrar', 'A2', 'verbs', '🚪', true, 'seeded'),
('to return', 'volver', 'A2', 'verbs', '↩️', true, 'seeded'),
('to stay', 'quedarse', 'A2', 'verbs', '🏠', true, 'seeded'),
('to change', 'cambiar', 'A2', 'verbs', '🔄', true, 'seeded'),
('to begin', 'comenzar', 'A2', 'verbs', '▶️', true, 'seeded'),
('to finish', 'terminar', 'A2', 'verbs', '🏁', true, 'seeded'),
('to continue', 'continuar', 'A2', 'verbs', '➡️', true, 'seeded'),
('to stop', 'parar', 'A2', 'verbs', '⏸️', true, 'seeded'),
('to wait', 'esperar', 'A2', 'verbs', '⏰', true, 'seeded'),
('to send', 'enviar', 'A2', 'verbs', '📤', true, 'seeded'),
('to receive', 'recibir', 'A2', 'verbs', '📥', true, 'seeded'),
('to pay', 'pagar', 'A2', 'verbs', '💳', true, 'seeded'),
('to cost', 'costar', 'A2', 'verbs', '💰', true, 'seeded'),
('to save (money)', 'ahorrar', 'A2', 'verbs', '💵', true, 'seeded'),
('to spend', 'gastar', 'A2', 'verbs', '💸', true, 'seeded'),
('to use', 'usar', 'A2', 'verbs', '🔧', true, 'seeded'),
('to repair', 'reparar', 'A2', 'verbs', '🔨', true, 'seeded'),
('to break', 'romper', 'A2', 'verbs', '💔', true, 'seeded'),

-- Complex Adjectives (30)
('interesting', 'interesante', 'A2', 'adjectives', '📚', true, 'seeded'),
('boring', 'aburrido', 'A2', 'adjectives', '😴', true, 'seeded'),
('important', 'importante', 'A2', 'adjectives', '❗', true, 'seeded'),
('necessary', 'necesario', 'A2', 'adjectives', '✅', true, 'seeded'),
('possible', 'posible', 'A2', 'adjectives', '👍', true, 'seeded'),
('impossible', 'imposible', 'A2', 'adjectives', '🚫', true, 'seeded'),
('different', 'diferente', 'A2', 'adjectives', '🔀', true, 'seeded'),
('same', 'mismo', 'A2', 'adjectives', '↔️', true, 'seeded'),
('similar', 'similar', 'A2', 'adjectives', '≈', true, 'seeded'),
('special', 'especial', 'A2', 'adjectives', '⭐', true, 'seeded'),
('normal', 'normal', 'A2', 'adjectives', '✔️', true, 'seeded'),
('strange', 'extraño', 'A2', 'adjectives', '🤨', true, 'seeded'),
('perfect', 'perfecto', 'A2', 'adjectives', '💯', true, 'seeded'),
('terrible', 'terrible', 'A2', 'adjectives', '😱', true, 'seeded'),
('wonderful', 'maravilloso', 'A2', 'adjectives', '🌟', true, 'seeded'),
('comfortable', 'cómodo', 'A2', 'adjectives', '🛋️', true, 'seeded'),
('dangerous', 'peligroso', 'A2', 'adjectives', '⚠️', true, 'seeded'),
('safe', 'seguro', 'A2', 'adjectives', '🔒', true, 'seeded'),
('quiet', 'tranquilo', 'A2', 'adjectives', '🤫', true, 'seeded'),
('noisy', 'ruidoso', 'A2', 'adjectives', '🔊', true, 'seeded'),
('busy', 'ocupado', 'A2', 'adjectives', '📅', true, 'seeded'),
('free (available)', 'disponible', 'A2', 'adjectives', '✅', true, 'seeded'),
('ready', 'listo', 'A2', 'adjectives', '✔️', true, 'seeded'),
('late', 'tarde', 'A2', 'adjectives', '⏰', true, 'seeded'),
('early', 'temprano', 'A2', 'adjectives', '🌅', true, 'seeded'),
('next', 'próximo', 'A2', 'adjectives', '➡️', true, 'seeded'),
('last', 'último', 'A2', 'adjectives', '🔚', true, 'seeded'),
('first', 'primero', 'A2', 'adjectives', '🥇', true, 'seeded'),
('second', 'segundo', 'A2', 'adjectives', '🥈', true, 'seeded'),
('third', 'tercero', 'A2', 'adjectives', '🥉', true, 'seeded'),

-- Abstract Nouns (30)
('thing', 'cosa', 'A2', 'abstract', '📦', true, 'seeded'),
('time', 'tiempo', 'A2', 'abstract', '⏰', true, 'seeded'),
('way', 'manera', 'A2', 'abstract', '🛤️', true, 'seeded'),
('person', 'persona', 'A2', 'abstract', '👤', true, 'seeded'),
('people', 'gente', 'A2', 'abstract', '👥', true, 'seeded'),
('life', 'vida', 'A2', 'abstract', '❤️', true, 'seeded'),
('death', 'muerte', 'A2', 'abstract', '💀', true, 'seeded'),
('world', 'mundo', 'A2', 'abstract', '🌍', true, 'seeded'),
('problem', 'problema', 'A2', 'abstract', '❓', true, 'seeded'),
('solution', 'solución', 'A2', 'abstract', '💡', true, 'seeded'),
('idea', 'idea', 'A2', 'abstract', '💭', true, 'seeded'),
('question', 'pregunta', 'A2', 'abstract', '❓', true, 'seeded'),
('answer', 'respuesta', 'A2', 'abstract', '💬', true, 'seeded'),
('story', 'historia', 'A2', 'abstract', '📖', true, 'seeded'),
('news', 'noticias', 'A2', 'abstract', '📰', true, 'seeded'),
('information', 'información', 'A2', 'abstract', 'ℹ️', true, 'seeded'),
('truth', 'verdad', 'A2', 'abstract', '✅', true, 'seeded'),
('lie', 'mentira', 'A2', 'abstract', '🤥', true, 'seeded'),
('name', 'nombre', 'A2', 'abstract', '📛', true, 'seeded'),
('word', 'palabra', 'A2', 'abstract', '💬', true, 'seeded'),
('language', 'idioma', 'A2', 'abstract', '🗣️', true, 'seeded'),
('reason', 'razón', 'A2', 'abstract', '🤔', true, 'seeded'),
('part', 'parte', 'A2', 'abstract', '🧩', true, 'seeded'),
('place', 'lugar', 'A2', 'abstract', '📍', true, 'seeded'),
('moment', 'momento', 'A2', 'abstract', '⏱️', true, 'seeded'),
('hour', 'hora', 'A2', 'abstract', '🕐', true, 'seeded'),
('minute', 'minuto', 'A2', 'abstract', '⏱️', true, 'seeded'),
('second (time)', 'segundo', 'A2', 'abstract', '⏱️', true, 'seeded'),
('example', 'ejemplo', 'A2', 'abstract', '📚', true, 'seeded'),
('advice', 'consejo', 'A2', 'abstract', '💡', true, 'seeded'),

-- Technology & Modern Life (15)
('computer', 'computadora', 'A2', 'technology', '💻', true, 'seeded'),
('phone', 'teléfono', 'A2', 'technology', '📞', true, 'seeded'),
('television', 'televisión', 'A2', 'technology', '📺', true, 'seeded'),
('radio', 'radio', 'A2', 'technology', '📻', true, 'seeded'),
('camera', 'cámara', 'A2', 'technology', '📷', true, 'seeded'),
('internet', 'internet', 'A2', 'technology', '🌐', true, 'seeded'),
('email', 'correo', 'A2', 'technology', '📧', true, 'seeded'),
('message', 'mensaje', 'A2', 'technology', '💬', true, 'seeded'),
('letter', 'carta', 'A2', 'technology', '✉️', true, 'seeded'),
('paper', 'papel', 'A2', 'technology', '📄', true, 'seeded'),
('pen', 'bolígrafo', 'A2', 'technology', '🖊️', true, 'seeded'),
('pencil', 'lápiz', 'A2', 'technology', '✏️', true, 'seeded'),
('notebook', 'cuaderno', 'A2', 'technology', '📓', true, 'seeded'),
('page', 'página', 'A2', 'technology', '📃', true, 'seeded'),
('photo', 'foto', 'A2', 'technology', '📸', true, 'seeded'),

-- Emotions & States (20)
('love', 'amor', 'A2', 'emotions', '❤️', true, 'seeded'),
('hate', 'odio', 'A2', 'emotions', '😡', true, 'seeded'),
('fear', 'miedo', 'A2', 'emotions', '😨', true, 'seeded'),
('anger', 'enfado', 'A2', 'emotions', '😠', true, 'seeded'),
('joy', 'alegría', 'A2', 'emotions', '😊', true, 'seeded'),
('sadness', 'tristeza', 'A2', 'emotions', '😢', true, 'seeded'),
('surprise', 'sorpresa', 'A2', 'emotions', '😲', true, 'seeded'),
('interest', 'interés', 'A2', 'emotions', '🤔', true, 'seeded'),
('peace', 'paz', 'A2', 'emotions', '☮️', true, 'seeded'),
('war', 'guerra', 'A2', 'emotions', '⚔️', true, 'seeded'),
('health', 'salud', 'A2', 'emotions', '💊', true, 'seeded'),
('illness', 'enfermedad', 'A2', 'emotions', '🤒', true, 'seeded'),
('pain', 'dolor', 'A2', 'emotions', '🤕', true, 'seeded'),
('luck', 'suerte', 'A2', 'emotions', '🍀', true, 'seeded'),
('hope', 'esperanza', 'A2', 'emotions', '🌟', true, 'seeded'),
('dream', 'sueño', 'A2', 'emotions', '💭', true, 'seeded'),
('memory', 'recuerdo', 'A2', 'emotions', '🧠', true, 'seeded'),
('experience', 'experiencia', 'A2', 'emotions', '📚', true, 'seeded'),
('opinion', 'opinión', 'A2', 'emotions', '💭', true, 'seeded'),
('feeling', 'sentimiento', 'A2', 'emotions', '❤️', true, 'seeded'),

-- Sports & Activities (15)
('sport', 'deporte', 'A2', 'sports', '⚽', true, 'seeded'),
('game', 'juego', 'A2', 'sports', '🎮', true, 'seeded'),
('team', 'equipo', 'A2', 'sports', '👥', true, 'seeded'),
('ball', 'pelota', 'A2', 'sports', '⚽', true, 'seeded'),
('soccer', 'fútbol', 'A2', 'sports', '⚽', true, 'seeded'),
('basketball', 'baloncesto', 'A2', 'sports', '🏀', true, 'seeded'),
('tennis', 'tenis', 'A2', 'sports', '🎾', true, 'seeded'),
('swimming', 'natación', 'A2', 'sports', '🏊', true, 'seeded'),
('exercise', 'ejercicio', 'A2', 'sports', '💪', true, 'seeded'),
('music', 'música', 'A2', 'sports', '🎵', true, 'seeded'),
('movie', 'película', 'A2', 'sports', '🎬', true, 'seeded'),
('party', 'fiesta', 'A2', 'sports', '🎉', true, 'seeded'),
('vacation', 'vacaciones', 'A2', 'sports', '🏖️', true, 'seeded'),
('hobby', 'pasatiempo', 'A2', 'sports', '🎨', true, 'seeded'),
('fun', 'diversión', 'A2', 'sports', '🎊', true, 'seeded');

-- ============================================================================
-- TOTAL: 500 Core Spanish Words
-- Distribution: ~100 A0, ~250 A1, ~150 A2
-- Source: CEFR Frequency Lists (Instituto Cervantes, Routledge)
-- ============================================================================
